openapi: 3.0.0
info:
  version: v0.1.0
  title: Menu
  description: 'The API for managing the menu for the restaurant.'
servers:
  - url: '{{menu_url}}'
paths:
  /menu:
    get:
      summary: Menu
      operationId: getMenus
      tags:
        - Menu
      responses:
        '200':
          description: Menu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuListing'
    post:
      summary: Menu
      operationId: addMenu
      tags:
        - Menu
      requestBody:
        description: Menu
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'        
      responses:
        '201':
          description: Menu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'   
  /menu/{menuId}:
    get:
      summary: Menu
      operationId: getMenu
      parameters:
        - name: menuId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string      
      tags:
        - Menu
      responses:
        '200':
          description: Menu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Menu'
    put:
      summary: Menu
      operationId: updateMenu
      tags:
        - Menu
      parameters:
        - name: menuId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string         
      requestBody:
        description: Menu
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'        
      responses:
        '204':
          description: Menu
    post:
      summary: Menu
      operationId: updateMenu
      tags:
        - Menu
      parameters:
        - name: menuId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string         
      requestBody:
        description: Menu
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'        
      responses:
        '204':
          description: Menu          
    delete:
      summary: Menu
      operationId: deleteMenu
      parameters:
        - name: menuId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string       
      tags:
        - Menu
      responses:
        '204':
          description: Menu                                           
components:
  schemas:
    MenuListing:
      type: array
      items:
        $ref: '#/components/schemas/Menu'
    Menu:
      type: object
      properties:
        menuId:
          type: integer
          format: int64
        text:
          description: 'The text for the menu.'
          type: string
        version:
          description: 'The version of the menu.'
          type: string          
        dateModified:
          description: 'The data the description was modified.'
          type: string
        dateCreated:
          description: 'The data the menu was created.'
          type: string
        inLanguage:
          description: 'The language of the menu'
          type: string
        MenuSections:
          type: array
          items:
            $ref: '#/components/schemas/MenuSection'   
    MenuSection:
      type: object
      properties:
        name:
          type: string
          description: 'The name of the menu section.'      
        description:
          type: string
          description: 'The description of the menu section.'  
        MenuItems:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'        
    MenuItem:
      type: object
      properties:
        name:
          type: string
          description: 'The name of the menu item.'      
        description:
          type: string
          description: 'The description of the menu item.'   
        price:
          type: string
          description: 'The price of the menu item.'             
                                    
