openapi: 3.0.0
info:
  version: v0.1.0
  title: Orders
  description: 'An API for managing orders from the restaurant.'
servers:
  - url: '{{orderUrl}}'
paths:
  /order:
    get:
      summary: Order
      operationId: getOrders
      tags:
        - Order
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListing'
    post:
      summary: Order
      operationId: addOrder
      tags:
        - Order
      requestBody:
        description: Order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'          
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListing'      
  /order/{orderId}:
    get:
      summary: Order
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string        
      tags:
        - Order
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListing'
    put:
      summary: Order
      operationId: updateOrder
      tags:
        - Order
      parameters:
        - name: orderId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string         
      requestBody:
        description: Order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'           
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListing'      
    delete:
      summary: Order
      operationId: deleteOrder
      tags:
        - Order
      parameters:
        - name: orderId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string         
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListing'                                        
components:
  schemas:
    OrderListing:
      type: array
      items:
        $ref: '#/components/schemas/Order'
    Order:
      type: object
      properties:
        orderId:
          type: string
        orderDelivery:
          description: The delivery of the parcel related to this order or order item.
          type: object
          format: orderDelivery
        customer:
          description: Party placing the order or paying the invoice.
          type: string
        paymentDue:
          description: The date that payment is due.
          type: object
          format: paymentDue
        confirmationNumber:
          description: A number that confirms the given order or payment has been received.
          type: string
        orderNumber:
          description: The identifier of the transaction.
          type: string
        paymentMethodId:
          description: An identifier for the method of payment used (e.g. the last 4 digits of the credit card).
          type: string
        billingAddress:
          description: The billing address for the order.
          type: object
          format: billingAddress
        orderedItem:
          description: The item ordered.
          type: string
        orderDate:
          description: Date order was placed.
          type: string
        paymentMethod:
          description: The name of the credit card or other method of payment for the order.
          type: object
          format: paymentMethod
        discountCode:
          description: Code used to redeem a discount.
          type: string
        orderStatus:
          description: The current status of the order.
          type: object
          format: orderStatus
        discount:
          description: Any discount applied (to an Order).
          type: string
