openapi: 3.0.0
info:
  version: v0.1.0
  title: Reviews
  description: 'This is an API for managing the reviews of the restaurant.'
servers:
  - url: '{{baseUrl}}'
paths:
  /reviews:
    get:
      summary: Review
      operationId: getReviews
      tags:
        - Review
      responses:
        '200':
          description: Review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewListing'
    post:
      summary: Review
      operationId: addReview
      tags:
        - Review
      requestBody:
        description: Review
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'           
      responses:
        '201':
          description: Review    
  /reviews/{reviewId}:
    get:
      summary: Review
      operationId: getReview
      parameters:
        - name: reviewId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string         
      tags:
        - Review
      responses:
        '200':
          description: Review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
    put:
      summary: Review
      operationId: updateReview
      parameters:
        - name: reviewId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string         
      tags:
        - Review
      requestBody:
        description: Review
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'             
      responses:
        '204':
          description: Review             
    delete:
      summary: Review
      operationId: deleteReview
      parameters:
        - name: reviewId
          in: path
          description: The unique id.
          required: true
          schema:
            type: string         
      tags:
        - Review
      responses:
        '204':
          description: Review                      
components:
  schemas:
    ReviewListing:
      type: array
      items:
        $ref: '#/components/schemas/Review'
    Review:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dateModified:
          description: The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed.
          type: string
        datePublished:
          description: Date of first broadcast/publication.
          type: string
        author:
          description: The author of this content or rating. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangeably.
          type: string
        reviewBody:
          description: The actual body of the review.
          type: string
        itemReviewed:
          description: The item that is being reviewed/rated.
          type: object
          format: itemReviewed
        reviewRating:
          description: 'The rating given in this review. Note that reviews can themselves be rated. The ```reviewRating``` applies to rating given by the review. The [[aggregateRating]] property applies to the review itself, as a creative work.'
          type: object
          format: reviewRating